# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Latest"
  url = "#talks_featured"
  weight = 10
  
#[[main]]
#  name = "Upcoming"
#  url = "#publications_featured"
#  weight = 1

#[[main]]
#  name = "Posts"
#  url = "#posts"
#  weight = 3

[[main]]
  name = "Tools"
  url = "#tool"
  weight = 20

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 30

[[main]]
  name = "Apps"
  url = "#app"
  weight = 40

[[main]]
  name = "Code"
  url = "#code"
  weight = 50

[[main]]
  name = "People"
  url = "#people"
  weight = 60
  
[[main]]
  name = "Publications"
  url = "publication"
  weight = 70


[[main]]
  name = "Tags"
  url = "#tags"
  weight = 80

[[main]]
  name = "Talks"
  url = "talk"
  weight = 90


#[[main]]
#  name = "Contact"
#  url = "#contact"
#  weight = 7

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 7
