image: debian:buster-slim

before_script:
  - apt-get update 
  - apt-get -y install pandoc pandoc-citeproc r-base git 
  - apt-get -y install libxml2-dev libcurl4-openssl-dev libssl-dev
  - apt-get -y install texlive-latex-recommended
  - R -e "install.packages(c('readr','remotes','zip', 'RefManageR'), repos='http://cran.rstudio.com')"
  - R -e "remotes::install_github('kwb-r/algoliar')"
  - R -e "remotes::install_github('rstudio/blogdown')"
  - R -e "blogdown::install_hugo()"

pages:
  script:
    - R -e "file.copy('config/_default/config.toml', 'config.toml', overwrite = TRUE)"
    - R -e "blogdown::build_site()"
#    - R -e "algoliar::algolia_post_batch()" 
  artifacts:
    paths:
      - public
  only:
    - master
