image: debian:buster-slim

before_script:
  - apt-get update 
  - sudo apt-get --install-suggests install pandoc pandoc-citeproc r-base git 
  - sudo apt-get --install-suggests apt-get -y install libxml2-dev libcurl4-openssl-dev libssl-dev
  - R -e "install.packages(c('remotes','zip', 'RefManageR'), repos='http://cran.rstudio.com')"
  - R -e "remotes::install_github('rstudio/blogdown')"
  - R -e "blogdown::install_hugo()"

pages:
  script:
    - R -e "file.copy('config/_default/config.toml', 'config.toml', overwrite = TRUE)"
    - R -e "blogdown::build_site()"
  artifacts:
    paths:
      - public
  only:
    - master
