language: r
dist: xenial
sudo: true
branches:
  only:
    - dev
cache:
  packages: yes
  directories:
    - $HOME/bin
before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh
script:
  - ./_build.sh
  - ./_deploy.sh
 