language: r
dist: xenial
latex: false

branches:
  only:
    - hugo-academic_4.6.2

cache:
  packages: yes
  directories:
    - $HOME/bin

script:
  - Rscript -e "blogdown::install_hugo(version = '0.58.3', force = TRUE)"
  - Rscript -e "blogdown::hugo_version()"
  - Rscript -e "fs::dir_ls('.')"
# Copying needed as blogdown expects "config.toml" in root_dir
  - Rscript -e "file.copy('config/_default/config.toml', 'config.toml', overwrite = TRUE)"
# Generate the website
  - Rscript -e "blogdown::build_site()"
# Automate upload of "index.json" to Algolia
# Sys.setenv(algolia_app_id = "my_app_id",
#            algolia_api_key = "my_api_key",
#            algolia_index_name = "my_index_name")
# These variables are defined in the Travis CI as 
# protected environment variables, configured at:
# https://travis-ci.org/KWB-R/fakin/settings
  - Rscript -e "algoliar::algolia_post_batch()"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_PAT
  on:
    branch: hugo-academic_4.6.2
  local_dir: public
