language: r
dist: trusty
sudo: false
before_install:
  - sudo -A add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install gcc-4.9
  - sudo apt-get --allow-unauthenticated upgrade libstdc++6
branches:
  only:
    - master
cache:
  packages: yes
  directories:
    - $HOME/bin
pandoc_version: 2.5
before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh
script:
  - ./_build.sh
  - ./_deploy.sh
 
